# Tire Parameters Configuration

[front_tire_0]
REF_M	=	2.2
SLOPE_0	=	4.0
SLOPE_1	=	6.5
ADHESION	=	20
X_MULT	=	1.4
SLOPE_0_X	=	0.8
SLOPE_1_X	=	1.4
M_CLAMP	=	5

[rear_tire_0]
REF_M	=	2.2
SLOPE_0	=	3.8
SLOPE_1	=	6.0
ADHESION	=	20
X_MULT	=	1.4
SLOPE_0_X	=	0.8
SLOPE_1_X	=	1.4
M_CLAMP	=	5

[base_path]
path = "../ohyeah2389_modkart_class2/data"
front_tire_0_lat_file = "tire_kart_sprint_front_lat.lut"
front_tire_0_long_file = "tire_kart_sprint_front_long.lut"
rear_tire_0_lat_file = "tire_kart_sprint_rear_lat.lut"
rear_tire_0_long_file = "tire_kart_sprint_rear_long.lut"

[ranges]
by_twentys = 400
by_hundreds = 3000
by_fivehundreds = 40000
